# Generated by Django 5.0.2 on 2024-02-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
